name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:    # allows manual runs

permissions:
  contents: write      # allow pushing SVGs back to the repo

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # —— Isometric Commit Calendar ——
      - name: Generate commit calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_calendar: true
          output_file: metrics-calendar.svg

      # —— Starred Topics ——
      - name: Generate starred topics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_topics: true               # starred topics
          output_file: metrics-starred-topics.svg

      # —— Languages from Star Lists ——
      - name: Generate languages from star lists
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_starlists_languages: true  # languages from starred repos
          output_file: metrics-languages-starred.svg

      # —— Repository Traffic ——
      - name: Generate repository traffic
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_traffic: true
          output_file: metrics-traffic.svg

      # —— WakaTime Coding Activity ——
      - name: Generate WakaTime activity
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_wakatime: true
          output_file: metrics-wakatime.svg

      - name: Commit and push SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics SVGs"
          file_pattern: "metrics-*.svg"
