name: Generate Metrics

on:
  schedule:
    # every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # allows manual runs

permissions:
  contents: write    # allow pushing SVGs back to the repo

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # —— Isometric Commit Calendar ——
      - name: Generate commit calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_calendar: true
          output_file: metrics-calendar.svg

      # —— Starred Topics ——
      - name: Generate starred topics report
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_starred_topics: true
          output_file: metrics-starred-topics.svg

      # —— Languages from Star Lists ——
      - name: Generate languages from starred repos
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_languages_starred: true
          output_file: metrics-languages-starred.svg

      # —— Repositories Traffic ——
      - name: Generate repository traffic report
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_traffic: true
          output_file: metrics-traffic.svg

      # —— WakaTime Coding Activity ——
      - name: Generate WakaTime activity report
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_wakatime: true
          output_file: metrics-wakatime.svg

      - name: Commit and push all reports
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update all metrics SVGs"
          file_pattern: "metrics-*.svg"
