name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'    # every day at midnight UTC
  workflow_dispatch:         # manual trigger

permissions:
  contents: write            # allow pushing generated SVGs

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------------- Isometric Commit Calendar ----------------
      - name: Generate commit calendar
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_isocalendar: yes               # isometric calendar
          isocalendar_duration: full-year       # entire year
          filename: metrics-calendar.svg
      - name: Commit calendar SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics-calendar.svg"
          file_pattern: metrics-calendar.svg

      # ---------------- Starred Topics ----------------
      - name: Generate starred topics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_topics: yes                    # topics cloud
          plugin_topics_mode: starred           # only starred repos
          filename: metrics-starred-topics.svg
      - name: Commit starred topics SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics-starred-topics.svg"
          file_pattern: metrics-starred-topics.svg

      # ---------------- Languages from Star Lists ----------------
      - name: Generate languages from starred repos
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_starlists: yes                 # enable star lists plugin
          plugin_starlists_languages: yes       # language distribution
          filename: metrics-languages-starred.svg
      - name: Commit languages-starred SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics-languages-starred.svg"
          file_pattern: metrics-languages-starred.svg

      # ---------------- Repository Traffic ----------------
      - name: Generate repository traffic stats
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_traffic: yes                   # traffic (clones / views)
          filename: metrics-traffic.svg
      - name: Commit traffic SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics-traffic.svg"
          file_pattern: metrics-traffic.svg

      # ---------------- WakaTime Coding Activity ----------------
      - name: Generate WakaTime activity
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: FedericoQuartieri
          plugin_wakatime: yes                  # requires public WakaTime profile
          wakatime_username: FedericoQuartieri   # change if different username
          filename: metrics-wakatime.svg
      - name: Commit wakatime SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics-wakatime.svg"
          file_pattern: metrics-wakatime.svg
