name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'       # ogni giorno a mezzanotte UTC
  workflow_dispatch:         # permette l’esecuzione manuale

permissions:
  contents: write            # necessario per fare push di METRICS.md

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate metrics report
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}        # ← qui il tuo PAT
          user: FedericoQuartieri                    # ← il tuo username GitHub
          plugin_languages: true                     # abilita “Top Languages”
          plugin_stats: true                         # abilita “Stats generali”
          plugin_repositories_affiliations: true     # include i repo di organizzazioni
          plugin_repositories_forks: true            # include i fork a cui hai contribuito
          output_file: METRICS.md                    # file di output
          
      - name: Commit and push report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics report"
          file_pattern: METRICS.md
