name: Generate Metrics

on:
  schedule:
    # every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:    # allows manual runs

permissions:
  contents: write      # needed to push METRICS.md back to the repo

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate metrics report
        uses: lowlighter/metrics@v3.34
        with:
          plugins: |
            languages
            stats
          languages_include_orgs: true    # <— spostato sotto with
          languages_include_forks: true   # <— spostato sotto with
          output_file: METRICS.md
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Commit and push report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics report"
          file_pattern: METRICS.md
