name: Generate Individual Metrics

on:
  schedule:
    - cron: "0 0 * * *"      # ogni giorno, mezzanotte UTC
  workflow_dispatch:         # avvio manuale

permissions:
  contents: write
# 
env:
  METRICS_TOKEN:  ${{ secrets.METRICS_TOKEN }}
  WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      ##################################################
      # 1. Isometric commit calendar
      ##################################################
      - name: Commit calendar
        uses: lowlighter/metrics@v3.34
        with:
          token:      ${{ env.METRICS_TOKEN }}
          user:       FedericoQuartieri
          base:       ""                         # niente header/attività
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename:   metrics-calendar.svg


      ##################################################
      # 2. Starred topics
      ##################################################
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons



      ##################################################
      # 3. WakaTime
      ##################################################
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}


      ##################################################
      # 4. Languages activity
      ##################################################

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_ignored: >-
              PostScript, Fortran, Makefile, Shell, TeX, Rof Manpage
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 40

         
      ##################################################
      # 5. Coding habits and activity 2
      ################################################## 

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
        
        

      ##################################################
      # Commit & push tutti gli SVG creati
      ##################################################
      - name: Commit and push SVGs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics SVGs"
          file_pattern:    metrics-*.svg
